# Generated by Django 3.2.22 on 2023-11-26 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='distributor_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=90)),
                ('pin', models.IntegerField()),
                ('proof_id', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='medicine_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('details', models.CharField(max_length=100)),
                ('mnf_date', models.DateField()),
                ('exp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='pharmacy_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('proof_id', models.FileField(upload_to='')),
                ('post', models.CharField(max_length=20)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='pharmacyrequest_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('MEDICINE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.medicine_table')),
                ('PHAARMACY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.pharmacy_table')),
            ],
        ),
        migrations.CreateModel(
            name='distributorrequest_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.distributor_table')),
                ('MEDICINE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.medicine_table')),
            ],
        ),
        migrations.AddField(
            model_name='distributor_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.login_table'),
        ),
    ]
