# Generated by Django 3.2.22 on 2023-12-08 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('phone_no', models.BigIntegerField()),
                ('order', models.IntegerField()),
                ('date', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.medicine_table')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.orders_table')),
            ],
        ),
    ]
