# Generated by Django 3.2.22 on 2023-12-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0002_order_details_orders_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders_table',
            old_name='order',
            new_name='total',
        ),
    ]
