# Generated by Django 3.2.22 on 2023-12-26 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0003_rename_order_orders_table_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyrequest_table',
            name='DISTRIBUTOR',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='med_app.distributor_table'),
            preserve_default=False,
        ),
    ]
