# Generated by Django 3.2.22 on 2023-12-26 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0004_pharmacyrequest_table_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_table',
            name='PHAARMACY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='med_app.pharmacy_table'),
            preserve_default=False,
        ),
    ]
