# Generated by Django 3.2.22 on 2023-12-28 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0005_orders_table_phaarmacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders_table',
            name='PHAARMACY',
        ),
        migrations.CreateModel(
            name='pharmacy_stock_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('MEDICINE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.medicine_table')),
                ('PHAARMACY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.pharmacy_table')),
            ],
        ),
        migrations.CreateModel(
            name='distributor_stock_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('DISTRIBUTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.distributor_table')),
                ('MEDICINE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.medicine_table')),
            ],
        ),
    ]
