# Generated by Django 5.0.1 on 2024-01-15 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0006_auto_20231228_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='distributor_medicine_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MEDICINE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.medicine_table')),
                ('REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.distributorrequest_table')),
            ],
        ),
        migrations.CreateModel(
            name='pharmacy_medicine_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MEDICINE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.medicine_table')),
                ('PHAARMACY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.pharmacyrequest_table')),
            ],
        ),
    ]
