# Generated by Django 5.0.1 on 2024-01-15 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0007_distributor_medicine_table_pharmacy_medicine_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy_medicine_table',
            name='MEDICINE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.distributor_medicine_table'),
        ),
        migrations.CreateModel(
            name='order_medicine_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.pharmacy_medicine_table')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.orders_table')),
            ],
        ),
    ]
