# Generated by Django 5.0.1 on 2024-01-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0008_alter_pharmacy_medicine_table_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor_medicine_table',
            name='status',
            field=models.CharField(default='available', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacy_medicine_table',
            name='status',
            field=models.CharField(default='available', max_length=15),
            preserve_default=False,
        ),
    ]
