# Generated by Django 5.0.1 on 2024-01-15 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0009_distributor_medicine_table_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_medicine_details',
            name='medicine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.distributor_medicine_table'),
        ),
    ]
