from django.urls import path

from med_app import views
from med_app.views import disregistercode

urlpatterns=[
    path('',views.main,name='main'),
    path('DISTRIBUTORNREGISTERATION',views.DISTRIBUTORNREGISTERATION,name='DISTRIBUTORNREGISTERATION'),
    path('PHARMACYREGISTERATION', views.PHARMACYREGISTERATION, name='PHARMACYREGISTERATION'),
    path('ACCEPTREJECTPHARMACY', views.ACCEPTREJECTPHARMACY, name='ACCEPTREJECTPHARMACY'),
    path('ADDMANAGEMEDICINE', views.ADDMANAGEMEDICINE, name='ADDMANAGEMEDICINE'),
    path('ADDMEDICINE', views.ADDMEDICINE, name='ADDMEDICINE'),
    path('ACCEPTREJECTDISTRIBUTOR_REQUEST', views.ACCEPTREJECTDISTRIBUTOR_REQUEST, name='ACCEPTREJECTDISTRIBUTOR_REQUEST'),
    path('ACCEPTREJECTDISTRIBUTOR', views.ACCEPTREJECTDISTRIBUTOR, name='ACCEPTREJECTDISTRIBUTOR'),
    path('BLOCKUNBLOCKDISTRUBUTOR', views.BLOCKUNBLOCKDISTRUBUTOR, name='BLOCKUNBLOCKDISTRUBUTOR'),
    path('DISTRIBUTORHOME', views.DISTRIBUTORHOME, name='DISTRIBUTORHOME'),
    path('DISTRIBUTORPACCEPTREJECT', views.DISTRIBUTORPACCEPTREJECT, name='DISTRIBUTORPACCEPTREJECT'),
    path('DISTRIBUTORSENDREQUEST', views.DISTRIBUTORSENDREQUEST, name='DISTRIBUTORSENDREQUEST'),
    path('dSENDREQUEST/<int:id>',views.dSENDREQUEST,name='dSENDREQUEST'),
    path('reject_dis_req/<int:id>',views.reject_dis_req,name='reject_dis_req'),
    path('Accept_dis_req/<int:id>',views.Accept_dis_req,name='Accept_dis_req'),
    path('DISTRIBUTORSTOCKUPDATE', views.DISTRIBUTORSTOCKUPDATE, name='DISTRIBUTORSTOCKUPDATE'),
    path('ADDANDMANAGEBILL', views.ADDANDMANAGEBILL, name='ADDANDMANAGEBILL'),
    path('ADDBILL/<int:id>', views.ADDBILL, name='ADDBILL'),
    path('BILLNOW', views.BILLNOW, name='BILLNOW'),
    path('CHECKMEDICINE', views.CHECKMEDICINE, name='CHECKMEDICINE'),
    path('PHARMACYHOME', views.PHARMACYHOME, name='PHARMACYHOME'),
    path('PHARMACYSENDREQUEST', views.PHARMACYSENDREQUEST, name='PHARMACYSENDREQUEST'),
    path('VIEWDISTRIBUTOR', views.VIEWDISTRIBUTOR, name='VIEWDISTRIBUTOR'),
    path('logout', views.logout, name='logout'),
    path('logincode', views.logincode, name='logincode'),
    path('ADMINHOME', views.ADMINHOME, name='ADMINHOME'),
    path('Accept_dis/<int:id>', views.Accept_dis, name='Accept_dis'),
    path('reject_dis/<int:id>', views.reject_dis, name='reject_dis'),
    path('Acceptp_dis/<int:id>', views.Acceptp_dis, name='Acceptp_dis'),
    path('rejectp_dis/<int:id>', views.rejectp_dis, name='rejectp_dis'),
    path('blockd_dis/<int:id>', views.blockd_dis, name='blockd_dis'),
    path('unblockd_dis/<int:id>', views.unblockd_dis, name='unblockd_dis'),
    path('acceptpd_dis/<int:id>', views.acceptpd_dis, name='accpetpd_dis'),
    path('rejectpd_dis/<int:id>', views.rejectpd_dis, name='rejectpd_dis'),
    path('disregistercode', views.disregistercode, name='disregistercode'),
    path('dispharmacycode', views.dispharmacycode, name='dispharmacycode'),
    path('medcode',views.medcode,name='medcode'),
    path('delete_med/<int:id>',views.delete_med,name='delete_med'),
    path('EDITMEDICINE/<int:id>',views.EDITMEDICINE,name='EDITMEDICINE'),
    path('edit_medcode',views.edit_medcode,name='edit_medcode'),
    path('ACCEPTREJECTDISTRIBUTOR_search',views.ACCEPTREJECTDISTRIBUTOR_search,name='ACCEPTREJECTDISTRIBUTOR_search'),
    path('ADDMANAGEMEDICINE_search',views.ADDMANAGEMEDICINE_search,name='ADDMANAGEMEDICINE_search'),
    path('BLOCKUNBLOCKDISTRUBUTOR_search',views.BLOCKUNBLOCKDISTRUBUTOR_search,name='BLOCKUNBLOCKDISTRUBUTOR_search'),
    path('ACCEPTREJECTPHARMACY_search', views.ACCEPTREJECTPHARMACY_search, name='ACCEPTREJECTPHARMACY_search'),
    path('DISTRIBUTORSENDREQUEST_search', views.DISTRIBUTORSENDREQUEST_search, name='DISTRIBUTORSENDREQUEST_search'),
    path('DISTRIBUTORPACCEPTREJECT_search', views.DISTRIBUTORPACCEPTREJECT_search, name='DISTRIBUTORPACCEPTREJECT_search'),
    path('VIEWDISTRIBUTOR_search', views.VIEWDISTRIBUTOR_search, name='VIEWDISTRIBUTOR_search'),
    path('PHARMACYSENDREQUEST_search', views.PHARMACYSENDREQUEST_search, name='PHARMACYSENDREQUEST_search'),
    path('ADDANDMANAGEBILL_search', views.ADDANDMANAGEBILL_search, name='ADDANDMANAGEBILL_search'),
    path('CHECKMEDICINE_search', views.CHECKMEDICINE_search, name='CHECKMEDICINE_search'),
    path('add', views.add, name='add'),
    path('addbillnow', views.addbillnow, name='addbillnow'),
    path('SENDREQUEST/<int:id>', views.SENDREQUEST, name='SENDREQUEST'),
    path('selcdistri', views.selcdistri, name='selcdistri'),
    path('send_req_post', views.send_req_post, name='send_req_post'),
    path('drequest', views.drequest, name='drequest'),
    path('andviewproducts',views.andviewproducts,name='andviewproducts'),
    path('viewstatus', views.viewstatus, name='viewstatus'),

]
